// Generated with Shader Minifier 1.5.1 (https://github.com/laurentlb/Shader_Minifier/)
#ifndef POST_INL_
# define POST_INL_
# define VAR_i "m"
# define VAR_m "f"
# define VAR_o "i"

const char *post_frag =
 "#version 130\n"
 "const vec2 v=vec2(1920,1080);"
 "uniform int f;"
 "uniform sampler2D i;"
 "out vec4 m;"
 "const int a[3]=int[3](3,4,20);"
 "vec3 t(float f)"
 "{"
   "vec4 v=vec4(1,0,0,3);"
   "return.6*mix(v.xxx,clamp(abs(fract(vec3(f)+v.xyz)*6-v.www)-v.xxx,0,1),.5);"
 "}"
 "const vec4 s[3]=vec4[3](vec4(4,28,.5,0),vec4(64,84,.2,0),vec4(100,120,.2,0));"
 "void main()"
 "{"
   "vec2 c=gl_FragCoord.xy/v.xy;"
   "m=texture(i,c);"
   "c.y=1.-c.y;"
   "float x=float(16),y=float(13);"
   "c*=vec2(x,y);"
   "float z=float(f)/44100*(127./60.);"
   "vec2 d=fract(c);"
   "int u=int(floor(c.x)),C=int(floor(c.y));"
   "vec3 n=vec3(.4);"
   "n.x=u%4==0?"
     ".5:"
     "0.;"
   "vec3 D=mix(n*.3,n,1.-(d.x<.05||d.x>.49&&d.x<.51||d.y<.05?"
     "1.:"
     "0.));"
   "if(u==int(mod(floor(z),x))&&C==int(mod(floor(z/x),y)))"
     "D=fract(z)<.5?"
       "d.x<.5?"
         "vec3(.7,.7,.1):"
         "n:"
       "d.x<.5?"
         "n:"
         "vec3(.7,.7,.1);"
   "u+=16*C;"
   "for(int v=0;v<3;v++)"
     "if(a[v]==u)"
       "D+=vec3(.2,1,.2);"
   "if(d.y>.4&&d.y<.6)"
     "for(int v=0;v<3;v++)"
       "if(s[v].y>u&&s[v].x<u)"
         "D+=t(s[v].z);"
   "if(u>208)"
     "D=vec3(0);"
   "m=mix(m,vec4(D,1),.2);"
 "}";

#endif // POST_INL_
